### PR TITLE
Lecture 13-b

### PR DESCRIPTION
**Pull request by amallia**
Jigsaw puzzles and colorization are some techniques that are being explored to solve the self-supervised problem. It consists of training a model like AlexNet or ResNet on a specific task with the goal of learning image representation and then training the same model on a different task like image classification or object detection. Using a small amount of data is favorable, this is known as few-shot learning. How well are these approaches performing?

-- Second part of Lecture 13 (6 May 2019) by Kevin Ayuque and Wei-yun. Edited by Antonio Mallia

### CODE REVIEW

**Comment by Atcold** [comment]
Plz, edit the first message, similarly to how it's done in #1.
The summary should be around 50/70 words.

**Comment by amallia** [comment]
> Plz, edit the first message, similarly to how it's done in #1.
> The summary should be around 50/70 words.

Updated. Let me know, thanks

**Comment by Atcold** [comment]
Screenshot 2019-05-20 18 24 20

**Comment by amallia** [comment]
@Atcold I received an email with a screenshot, but I cannot find it anymore on Github. Did you remove it? Was it a false alarm? Thanks

**Comment by Atcold** [comment]
Hahahahahahahahah!

**Pull request merged**
