### PR TITLE
Lab 07

### PR DESCRIPTION
**Pull request by bmahlbrand**
As Convolutional Neural Networks naturally lend themselves to images, RNNs (including LSTMs and Transformers) lend themselves similarly to sequential data (which could additionally include each step being images). These might take the form of time series, speech recognition, learning grammars (language translators, name generators, etcetera) or musical rhythms - among others. More precisely one can define them to be directed graphs mapping to a temporal sequence.

Benjamin Ahlbrand (editor), Xingyu Ding, Haoran Anthony Su

Lab07 03/12/2019

### CODE REVIEW

**Comment by Atcold** [comment]
PR summary and date are missing.
Plz, edit the first message, similarly to how it's done in #1.
Also, I think this is `Lab 07`.

**Comment by bmahlbrand** [comment]
wilco!

**Comment by Atcold** [comment]
Who or what is *wilco*?

**Comment by bmahlbrand** [comment]
Sorry, it's shorthand for "will comply" - I'll get this squared away this evening.

**Comment by bmahlbrand** [comment]
I hope I addressed your comments to your expectations!

**Comment by Atcold** [comment]
Very well, thanks.

**Pull request merged**
