### PR TITLE
moved KF parts in main.tex

### PR DESCRIPTION
**Pull request by karlafej**
Not sure where the arch/ Convolutional Nets belongs (chapter 7 at the moment), and whether it should be in the book at all as it was commented out in the original version of main.tex.

### CODE REVIEW

**Comment by Atcold** [comment]
Can you please specify *who* commented it out, and what part of the code you're talking about (put a link to the lines, so that we can investigate further).

**Comment by karlafej** [comment]
Seems to come from the commit dcdbc9a, June 29, Updates on Overleaf. 
```
- \input{lectures/03-a/theory}
+ %\input{lectures/03-a/theory}
```
in main.tex

**Comment by Atcold** [comment]
That file comes from #11. The title is https://github.com/Atcold/SP19-DL-collaborative-notes/pull/11/files#diff-ac335db300b3227944e5aa7f66ab37aaR1, so I believe Karla, Parvez, Gustavo, Yahui are dealing with CNNs. Perhaps we need to draw some attention in the chat?

**Comment by Atcold** [comment]
I'm seeing this, at the moment.

```
<<<<<<< karla
\input{lectures/04-a/practice}
%\input{prct/KF/convolution_demonstration}
%\input{prct/KF/automatic_differentiation}
%\input{prct/KF/img_classification_comparison}
=======
%\input{prct/KF/visualizing_2D_interpolations}
\input{prct/KF/convolution_demonstration}
%\input{prct/KF/automatic_differentiation}
\input{prct/KF/img_classification_comparison}
>>>>>>> master
```

Which one is correct?

**Comment by karlafej** [comment]
Everything here should be commented out.
I'll rather do a new PR on top of the last commit to be sure the order in \part{Practical \& applications}\label{prt:prct} is OK :-)

**Comment by Atcold** [comment]
Okay, please, go ahead.

**Pull request closed without merging**
