### PR TITLE
Move my 2 chapters and the orphan striding chapter

### PR DESCRIPTION
**Pull request by GusSand**
Moved my last 2 chapters and the unclaimed striding chapter.

### CODE REVIEW

**Comment by Atcold** [comment]
Orphan chapter 🥺

**Comment by bmahlbrand** [comment]
At least it took it in stride 🤔

**Comment by GusSand** [comment]
BTW, by orphan I mean no one had claimed it...

:)

**Comment by michaelgold** [comment]
> At least it took it in stride

He was committed.

**Pull request merged**
