### PR TITLE
Lab 10 – bug fix

### PR DESCRIPTION
**Pull request by yanbixing**
Autoencoder is a an unsupervised learning of efficient data coding. With neural network layers as encoder and decoder, the aim of an autoencoder is to restore its input data at the output. Traditionally, autoencoders are used for dimensionality reduction; while recently, this concept are more widely used for learning the generative model of data. Here, we give a short summarization and some example codes of the basic class structure for autoencoders.

-- Lab 10 theory (14 Apr 2019) by Bixing Yan, Chengze Zuo. Edited by Yavuz Sunor.
-- Lab 10 coding (11 Apr 2019) by Chengze Zuo.

### CODE REVIEW

**Comment by yanbixing** [comment]
> Fixed the bugs. Sorry for that we were using an old version. It cause some problem during merge (Like the wrong citation of Lab 09 figures). Now, this version is fully updated and able to compile.
> 
> Note: However, the lecture 11 seems incomplete when we update. After we temporarily comment it. The files compiles well. There is the picture of successful compiling from overleaf.



> Autoencoder is a an unsupervised learning of efficient data coding. With neural network layers as encoder and decoder, the aim of an autoencoder is to restore its input data at the output. Traditionally, autoencoders are used for dimensionality reduction; while recently, this concept are more widely used for learning the generative model of data. Here, we give a short summarization and some example codes of the basic class structure for autoencoders.
> 
> -- Lab 10 theory (14 Apr 2019) by Bixing Yan, Chengze Zuo. Edited by Yavuz Sunor.
> -- Lab 10 coding (11 Apr 2019) by Chengze Zuo.


###################################################################

Fixed the bugs. Sorry for that we were using an old version. It cause some problem during merge (Like the wrong citation of Lab 09 figures). Now, this version is fully updated and able to compile.

Note: However, the lecture 11 seems incomplete when we update. After we temporarily comment it. The files compiles well. There is the picture of successful compiling from overleaf.

WX20190508-210354@2x

**Comment by Atcold** [comment]
Rebase on top of master. You've already submitted all this code in #39.
Screenshot 2019-05-17 18 01 02

**Comment by yavuzsunor** [comment]
Hi Alfredo, I sent a new PR from my account for this issue to be solved.

**Comment by yanbixing** [comment]
Hi Alfredo,
Pls use yavuzsunor's update. Have no idea why we can see other people's commits in our repo. To keep safe, we start a new PR.

**Comment by Atcold** [comment]
Where's the new PR? Add a reference using the # and the PR number.

**Comment by yavuzsunor** [comment]
Hi Alfredo,
Bixing is my lecture notes mate. I've sent you the PR(#62) for lab10.

Thanks,
Yavuz

**Pull request closed without merging**
