### PR TITLE
Lecture 10-a

### PR DESCRIPTION
**Pull request by ZizouHe**
Supervised learning algorithms are not suitable for tasks like reasoning and lack-of-label classification. This is where unsupervised learning is needed. In unsupervised learning, we use energy-based method to learn probability distribution from data instead of producing a single prediction value. Several ways is then introduced to shape the energy function and to insure the energy is low on the empirical data domain and high elsewhere.

Author: Yunhao Li, Geyi Zhang and He Li.
Date: 04/15/2019

### CODE REVIEW

**Comment by Atcold** [comment]
Plz, edit the first message, similarly to how it's done in #1.
The summary should be around 50/70 words.

**Comment by Atcold** [comment]
The date is missing. Plz, check #1.

**Comment by ZizouHe** [comment]
> The date is missing. Plz, check #1.

Date is added.

**Comment by Atcold** [comment]
Thanks.

**Pull request merged**
