### PR TITLE
Add CC BY-NC-SA license

### PR DESCRIPTION
**Pull request by ricardobarroslourenco**
Refer to discussion at: https://github.com/Atcold/SP19-DL-collaborative-notes/issues/104#event-3019015460

### CODE REVIEW

**Comment by Atcold** [comment]
These are from last year LaTeX notes.
I thought you wanted to translate only the lectures' annotations.

**Comment by ricardobarroslourenco** [comment]
@Atcold initially I've looked into the previous year notes, and those seem pretty good too, and since they are _stable_ translation seems easier to attend (I'm not excluding current ones though)

**Comment by Atcold** [comment]
We are putting **a lot of effort** into *this year* notes.

**Comment by ricardobarroslourenco** [comment]
I see. So I wonder that this one's is better, and I should not use old info.

**Comment by Atcold** [comment]
This year we're changing a lot of stuff. Anyhow, I'm accepting this PR.

**Pull request merged**
