### PR TITLE
Lecture 08-a – bug fix

### PR DESCRIPTION
**Pull request by bellineq**
We remove the picture already defined in lectures/07-b,
Thank you.

### CODE REVIEW

**Comment by Atcold** [comment]
In #38 I said the label was already defined.
Was also the picture the exact same one?

**Comment by Atcold** [comment]
Just fix the label. You can keep the image...
I'm complaining about compilation errors.

**Comment by bellineq** [comment]
Hi, we add the fig back and change the name of the label,
Thank you!

**Comment by Atcold** [comment]
One more.

Screenshot 2019-05-18 14 35 51

Can you plz check the error messages when you compile your notes and see you haven't broken anything?

**Pull request merged**
