### PR TITLE
Lab 13

### PR DESCRIPTION
**Pull request by zcgeng**
The Truck Backer-Upper

In this lab, we looked at how to solve the Trucker-Backer Upper problem (a nonlinear control problem) where we have to design a controller which guides the track from an initial position to align itself at a loading dock by moving in the reverse direction only. We looked at how a two-stage neural network could be employed to solve this task where the first stage (emulator) learns the kinematics of the truck and the second stage (controller) takes the decision about the exact angle to turn at each backing step.

-- Lab 13 (04/30/2019) by Arnav Kansal & Xiao Jing. Edited bt Changgeng Zhao

### CODE REVIEW

**Comment by Atcold** [comment]
Plz, edit the first message, similarly to how it's done in #1.
The summary should be around 50/70 words.

**Comment by Atcold** [comment]
Also, there is no need to copy and paste all my notebook. Especially the truck part is irrelevant.

**Comment by zcgeng** [comment]
I removed the truck part and replaced some of the pasted code with text. Please check.

**Comment by Atcold** [comment]
Very good, thank you. These notes should help the reader understand the code, not simply have a duplicate. If I need to update stuff, I'll do it on the notebook. The notes are supposed to be teaching material.

**Pull request merged**
