### PR TITLE
Lab 01

### PR DESCRIPTION
**Pull request by dgodevais**
We reviewed some of the basic functionality a Jupyter Notebook offer its users and introduced the PyTorch framework with its Tensor objects. We practiced manipulating different types of tensors, including vectors and matrices which illustrated their construction and indexing features. We also visualized how linear transformations and non-linear transformations stretch a 2D space of points sampled from a Gaussian distribution. Linear transformations will stretch the space by rotation, scaling and/or sheer.

-- First part of Lab 01 (29 Jan 2019) by Yi Li and Reuben Juster. Edited by Dustin Godevais.

### CODE REVIEW

**Comment by Atcold** [comment]
Add authors and editor and point transformation by randomly initialised nets to the PR description.

**Comment by Atcold** [comment]
There are some issues with `\tightlist`, `\color{incolor}`, and `\color{outcolor}`.
Can you please fix it? Thanks.

Edit: fixed.

**Comment by Atcold** [comment]
screenshot 2019-02-06 13 31 46
Figures have some problem too...

**Comment by Atcold** [comment]
There are `\label{fig:mon}` everywhere! This creates a lot of warnings!
Did the reviewer compile a PDF at all?

**Comment by Atcold** [comment]
Can we please add the authors list to the PR description?
Thanks.

**Comment by dgodevais** [comment]
Done.

**Pull request merged**
