### PR TITLE
Lecture 03-b – original PR

### PR DESCRIPTION
**Pull request by ZacharyATanenbaum**
Hey Alfredo!

I hope I'm doing this correctly! Also - do you mind answering a few question before accepting this pull request?

In the cursive image where Dr. Lecun was speaking about the old term for having a Neural Network run over a new sized image the acronym is SDNN. I'm unsure if I'm hearing him correctly in the video - did he say SDNN means Space Discrepancy Neural Network?

Also, Dr. Lecun states that using a Convolutional Neural Network on a new input has a fancy french name. Was that name "Convolutional Et Eau"?

Thanks for the help! Let me know if I need to change anything!

Best,

Zach

### CODE REVIEW

**Comment by taegyunkim** [comment]
Please hold on to accepting this pull request. I'm in process of editing it.

**Comment by Atcold** [comment]
*SDD* stands for *Space Displacement Neural Net*. You can check out Yann's and friends' paper: «Matan, O., Burges, C. J., LeCun, Y., & Denker, J. S. (1992). [Multi-digit recognition using a space displacement neural network.](http://papers.nips.cc/paper/557-multi-digit-recognition-using-a-space-displacement-neural-network.pdf) In _Advances in neural information processing systems._».

Also, why are there 2 PRs?

**Comment by taegyunkim** [comment]
@ZacharyATanenbaum Mind closing this one? This one is not integrated into the main.tex and has few typos.

**Comment by ZacharyATanenbaum** [comment]
Sure, I'm going to be busy until later today (at work). I'll finish it up
tonight.

Le mar. 19 févr. 2019 à 12:27, Taegyun Kim <notifications@github.com> a
écrit :

**Comment by Atcold** [comment]
This got merged automatically by merging #14.

**Pull request merged**
