### PR TITLE
Added 11-b Poincare Embedding

### PR DESCRIPTION
**Pull request by aakritigupta0408**
Hierarchical representations of symbolic data can be embedded into hyperbolic space – more precisely an n-dimensional Poincaré ball. An efficient algorithm of Poincaré embeddings based on Riemannian optimization can outperform Euclidean embeddings significantly on data with latent hierarchies. The main challenge is that Riemannian manifolds optimization tools are much less developed than Euclidean tools.
– Second part of Lecture 11 (22 April 2019) by Aakriti Gupta, Huiyu Sun, and Manrique Vargas

### CODE REVIEW

**Comment by Atcold** [comment]
#54 and this do not have any description!!!
Plz, edit the first message, similarly to how it's done in #1.
The summary should be around 50/70 words.

**Comment by mv1742** [comment]
Hierarchical representations of symbolic data can be embedded into hyperbolic space – more precisely an n-dimensional Poincaré ball. An efficient algorithm of Poincaré embeddings based on Riemannian optimization can outperform Euclidean embeddings significantly on data with latent hierarchies. The main challenge is that in Riemannian manifolds optimization tools are much less developed than Euclidean tools.
– Second part of Lecture 11 (22 April 2019) by Aakriti Gupta, Huiyu Sun, and Manrique Vargas

**Comment by Atcold** [comment]
I'm confused. This PR has already happen and it's called #54.
What is this additional PR???

**Comment by machov** [comment]
This PR supersedes the other one, please ignore #54. Thanks!

**Pull request merged**
