### PR TITLE
Lecture 08-b

### PR DESCRIPTION
**Pull request by SohamMody**
In this section, we look at the applications of latent variable models in Object Detection which are Face Detection in Images and Keyword detection in speech data like Alexa or Hey, Siri. We also discuss various good and bad loss functions along with the 'collapse problem'. A good loss function would be such that it gives low energy to the correct answers and high energy to the incorrect ones.

-- Second part of Lecture 8 (1st April 2019) by  Yash Goel and Urwa Muaz. Edited by Soham Mody,

### CODE REVIEW

**Comment by Atcold** [comment]
PR summary, author list, and date are missing.
Plz, edit the first message, similarly to how it's done in #1.

**Comment by SohamMody** [comment]
In this section, we look at the applications of latent variable models in Object Detection which are Face Detection in Images and Keyword detection in speech. We also discuss various good and bad loss functions. 

-- Second part of Lecture 8 (1st April 2019) by  Yash Goel and Urwa Muaz. Edited by Soham Mody,

**Comment by Atcold** [comment]
The summary should be around 50/70 words.

**Comment by SohamMody** [comment]
Is it okay now?

**Pull request merged**
