### PR TITLE
Lab 08

### PR DESCRIPTION
**Pull request by sarthak96agarwal**
In this lab, we implement sequence modelling by using LSTM and RNN on 2 different examples. The fist task is sequence classification and the second task  is input echoing. Both of these tasks present a need to store the context of the sequence at every timestamp. Also, we compare the performance of LSTM and RNN models and find that LSTM is able to retain memory for longer time. We implement LSTM and RNN by passing the data in chunks instead and doing truncated bptt rather than full bptt.
-- Lab 8 (26 March 2019) by Raghav Jajodia, Ieshan Vaidya. Edited by Sarthak Agarwal

### CODE REVIEW

**Comment by Atcold** [comment]
PR summary, author list, and date are missing.
Plz, edit the first message, similarly to how it's done in #1.

**Comment by sarthak96agarwal** [comment]
Done.

**Comment by Atcold** [comment]
Thank you.

**Comment by Atcold** [comment]
I'm getting this. Plz, fix.

Screenshot 2019-05-18 14 42 04

**Comment by sarthak96agarwal** [comment]
Hi,
We tried to check the LaTeX code locally but did not face any such issue.
Is the issue solved now or you are still facing it?

Thanks
Sarthak Agarwal

**Pull request merged**
