### PR TITLE
Lab 14

### PR DESCRIPTION
**Pull request by sunghoonyang**
Images and texts can be formalized with graphs as they are connected grids with information contained in each node and edge. Graph contains vertexes and edges and the messages(information) associated. Deep learning on graph structure composes GNN. GNN learns embedding on graphs. 

-- Lab 14 by Yu Cao and Oussama Fatri. Edited by Sung Hoon Yang

### CODE REVIEW

**Comment by Atcold** [comment]
Plz, edit the first message, similarly to how it's done in #1.
The summary should be around 50/70 words.

**Comment by sunghoonyang** [comment]
Dear Alfredo,

I have reviewed the submission.

**Comment by Atcold** [comment]
Why did you shorten them?
My note

> The summary should be around 50/70 words.

was referred to the first message, here in the PR.

**Comment by sunghoonyang** [comment]
Dear Alfredo, 

I reverted to the original commit. Please review the submission again.

**Comment by Atcold** [comment]
Fantastic! Thank you!

**Pull request merged**
