### PR TITLE
Lab 04

### PR DESCRIPTION
**Pull request by Rae-Jiang**
add part of lab4 notes

### CODE REVIEW

**Comment by Atcold** [comment]
Why was this closed?

**Comment by Rae-Jiang** [comment]
Because we need to do more editing..

**Comment by Atcold** [comment]
You can still push your edits to this PR. I'm re-opening. Let me know when I can merge.

**Comment by NorthStar** [comment]
Hi @Atcold  this was pr-ed by mistake from the wrong branch (meant to PR to my branch https://github.com/NorthStar/SP19-DL-collaborative-notes/pull/1 ), prematurely before one member could even participate in the edits. 

Best to close and reopen a new one from the right branch when things are done, since PRs are meant to be reviewed for merges so we don't *accidentally* request merges.

Alternatively, to clear up issue history and to keep track of work to be done, we can keep this open and close it after opening a new issue that links to this one.

**Comment by Atcold** [comment]
Just force push your branch onto this branch, and you'll be pushing the new stuff 😉

**Comment by NorthStar** [comment]
I don't think there will be a `push --f` either way since everything so far is rebasable.

@Atcold  I wonder if you could make this into a draft PR, using this [bleeding edge](https://help.github.com/en/articles/changing-the-stage-of-a-pull-request) feature? That will make the software engineer in me happy. Primary concern wasn't merge conflicts but workflow integrity. Generally on github a PR is only opened if ready to go.

**Comment by Atcold** [comment]
You should be done with the writing, by now, no?
Why can't you push your current branch onto this? Like
```git
git push --force <remote> <localCorrectBranch>:<remotePullRequestBranch>
```

**Pull request closed without merging**
