### PR TITLE
Lecture 02-b – fixing caption

### PR DESCRIPTION
**Pull request by viveky23**
Edited Caption of image in Chapter 8

### CODE REVIEW

**Comment by Atcold** [comment]
There are two `\label{fig:sgd}`. This creates errors in the LaTeX compilation.
Please, use meaningful labels, and rebase on top of the latest master.

screenshot 2019-02-13 13 08 57

**Review by viveky23 — COMMENTED** [review]
I have changed the offending caption and label. We must have missed it towards the end before submission. Sorry for all the inconvenience caused.

**Comment by viveky23** [comment]
Hey, I rebased and force pushed it as requested. Apparently you can't do it from Overleaf and have to do it from terminal. Sorry for the delay. I had been out of town for a few days for a hackathon!

**Comment by Atcold** [comment]
This PR is adding `1,060` lines and removing `14`, changing `35` files in total!
Can you rebase your only commit on top of `master`?
Just get the latest `master` and cherry pick on top your only edit.

**Comment by viveky23** [comment]
> This PR is adding `1,060` lines and removing `14`, changing `35` files in total!
> Can you rebase your only commit on top of `master`?
> Just get the latest `master` and cherry pick on top your only edit.

Sorry, I dont have a lot of experience with github so screed up somehow. I hope it is fine now!

**Comment by Atcold** [comment]
Thanks.

**Pull request merged**
