### PR TITLE
Lecture 13-a – bug fix

### PR DESCRIPTION
**Pull request by mlstelmach**
I fixed issues Alfredo mentioned; please let me know if there's any remaining issues.

I also added Hormet's section so he doesn't have to add separately.

note: I had to comment out lecture 11-a for the whole document to compile

### CODE REVIEW

**Comment by Atcold** [comment]
> I fixed issues Alfredo mentioned

Where??? Mention issue with # and number.
Also, remove the comment from `main.tex` since now `master` is compiling just fine.

**Comment by mlstelmach** [comment]
the issues I fixed were changing image labels from fig.1 to appropriate names and I also added Hormet's section

what do you mean by # and number?

**Comment by Atcold** [comment]
Can you please merge master into your branch?
I cannot merge it due to a conflict, and GitHub seems having problems handling it.

**Comment by Atcold** [comment]
Thank you @michaelgold!

**Pull request merged**
